import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { cn } from '@/lib/utils'
import ModalProvider from '@/components/providers/modal-provider'

const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Chat page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    // wrap inside clerk auth provider
      <ClerkProvider> 
    <html lang="en" suppressHydrationWarning>
      {/* define dark mode background for better colour */}
      <body className={cn(
        font.className,
        "bg-white dark:bg-[#313338]"
        )}>
      
        {/* wrap children inside ThemeProvider for implement dark/light mode */}
        <ThemeProvider
          attribute='class'
          defaultTheme='dark'
          enableSystem={false}
          storageKey='main-theme'
        >
        <ModalProvider/>
        {children}
        </ThemeProvider>
        </body>
    </html>
      </ClerkProvider>
  )
}
